@coins-array=-> [
    * id:\bitcoin  symbol:\BTC
    * id:\ethereum  symbol:\ETH
    * id:\bitcoin-cash  symbol:\BCH
    * id:\ripple  symbol:\XRP
    * id:\litecoin  symbol:\LTC
    * id:\cardano  symbol:\ADA
    * id:\iota  symbol:\MIOTA
    * id:\dash  symbol:\DASH
    * id:\nem  symbol:\XEM
    * id:\monero  symbol:\XMR
    * id:\bitcoin-gold  symbol:\BTG
    * id:\eos  symbol:\EOS
    * id:\qtum  symbol:\QTUM
    * id:\neo  symbol:\NEO
    * id:\stellar  symbol:\XLM
    * id:\ethereum-classic  symbol:\ETC
    * id:\tron  symbol:\TRX
    * id:\omisego  symbol:\OMG
    * id:\lisk  symbol:\LSK
    * id:\populous  symbol:\PPT
    * id:\bitconnect  symbol:\BCC
    * id:\waves  symbol:\WAVES
    * id:\zcash  symbol:\ZEC
    * id:\hshare  symbol:\HSR
    * id:\stratis  symbol:\STRAT
    * id:\bitshares  symbol:\BTS
    * id:\ardor  symbol:\ARDR
    * id:\tether  symbol:\USDT
    * id:\nxt  symbol:\NXT
    * id:\verge  symbol:\XVG
    * id:\bytecoin-bcn  symbol:\BCN
    * id:\monacoin  symbol:\MONA
    * id:\steem  symbol:\STEEM
    * id:\augur  symbol:\REP
    * id:\dogecoin  symbol:\DOGE
    * id:\status  symbol:\SNT
    * id:\ark  symbol:\ARK
    * id:\binance-coin  symbol:\BNB
    * id:\komodo  symbol:\KMD
    * id:\veritaseum  symbol:\VERI
    * id:\decred  symbol:\DCR
    * id:\salt  symbol:\SALT
    * id:\einsteinium  symbol:\EMC2
    * id:\siacoin  symbol:\SC
    * id:\vechain  symbol:\VEN
    * id:\raiblocks  symbol:\XRB
    * id:\golem-network-tokens  symbol:\GNT
    * id:\electroneum  symbol:\ETN
    * id:\byteball  symbol:\GBYTE
    * id:\pivx  symbol:\PIVX
    * id:\vertcoin  symbol:\VTC
    * id:\tenx  symbol:\PAY
    * id:\power-ledger  symbol:\POWR
    * id:\basic-attention-token  symbol:\BAT
    * id:\digibyte  symbol:\DGB
    * id:\bytom  symbol:\BTM
    * id:\digixdao  symbol:\DGD
    * id:\kyber-network  symbol:\KNC
    * id:\qash  symbol:\QASH
    * id:\factom  symbol:\FCT
    * id:\aeternity  symbol:\AE
    * id:\maidsafecoin  symbol:\MAID
    * id:\gas  symbol:\GAS
    * id:\syscoin  symbol:\SYS
    * id:\walton  symbol:\WTC
    * id:\bitcoindark  symbol:\BTCD
    * id:\gxshares  symbol:\GXS
    * id:\0x  symbol:\ZRX
    * id:\bitbay  symbol:\BAY
    * id:\santiment  symbol:\SAN
    * id:\dragonchain  symbol:\DRGN
    * id:\zcoin  symbol:\XZC
    * id:\funfair  symbol:\FUN
    * id:\decentraland  symbol:\MANA
    * id:\cryptonex  symbol:\CNX
    * id:\iconomi  symbol:\ICN
    * id:\raiden-network-token  symbol:\RDN
    * id:\gnosis-gno  symbol:\GNO
    * id:\gamecredits  symbol:\GAME
    * id:\nexus  symbol:\NXS
    * id:\request-network  symbol:\REQ
    * id:\civic  symbol:\CVC
    * id:\monaco  symbol:\MCO
    * id:\metal  symbol:\MTL
    * id:\bancor  symbol:\BNT
    * id:\paypie  symbol:\PPP
    * id:\nav-coin  symbol:\NAV
    * id:\streamr-datacoin  symbol:\DATA
    * id:\aion  symbol:\AION
    * id:\metaverse  symbol:\ETP
    * id:\blocknet  symbol:\BLOCK
    * id:\chainlink  symbol:\LINK
    * id:\ethos  symbol:\ETHOS
    * id:\peercoin  symbol:\PPC
    * id:\edgeless  symbol:\EDG
    * id:\ink  symbol:\INK
    * id:\asch  symbol:\XAS
    * id:\storj  symbol:\STORJ
    * id:\sonm  symbol:\SNM
    * id:\ripio-credit-network  symbol:\RCN
    * id:\groestlcoin  symbol:\GRS
    * id:\substratum  symbol:\SUB
    * id:\rchain  symbol:\RHOC
    * id:\revain  symbol:\R
    * id:\achain  symbol:\ACT
    * id:\ubiq  symbol:\UBQ
    * id:\kin  symbol:\KIN
    * id:\dent  symbol:\DENT
    * id:\quantstamp  symbol:\QSP
    * id:\adx-net  symbol:\ADX
    * id:\aragon  symbol:\ANT
    * id:\pura  symbol:\PURA
    * id:\skycoin  symbol:\SKY
    * id:\time-new-bank  symbol:\TNB
    * id:\zencash  symbol:\ZEN
    * id:\cindicator  symbol:\CND
    * id:\enjin-coin  symbol:\ENJ
    * id:\loopring  symbol:\LRC
    * id:\singulardtv  symbol:\SNGLS
    * id:\jinn  symbol:\JINN
    * id:\particl  symbol:\PART
    * id:\agoras-tokens  symbol:\AGRS
    * id:\reddcoin  symbol:\RDD
    * id:\attention-token-of-media  symbol:\ATM
    * id:\counterparty  symbol:\XCP
    * id:\quantum-resistant-ledger  symbol:\QRL
    * id:\feathercoin  symbol:\FTC
    * id:\cloakcoin  symbol:\CLOAK
    * id:\mercury  symbol:\MER
    * id:\rise  symbol:\RISE
    * id:\delphy  symbol:\DPY
    * id:\pepe-cash  symbol:\PEPECASH
    * id:\potcoin  symbol:\POT
    * id:\minexcoin  symbol:\MNX
    * id:\viacoin  symbol:\VIA
    * id:\yoyow  symbol:\YOYOW
    * id:\wings  symbol:\WINGS
    * id:\red-pulse  symbol:\RPX
    * id:\cobinhood  symbol:\COB
    * id:\hive  symbol:\HVN
    * id:\wabi  symbol:\WABI
    * id:\kucoin-shares  symbol:\KCS
    * id:\digitalnote  symbol:\XDN
    * id:\voxels  symbol:\VOX
    * id:\whitecoin  symbol:\XWC
    * id:\cofound-it  symbol:\CFI
    * id:\library-credit  symbol:\LBC
    * id:\rlc  symbol:\RLC
    * id:\pillar  symbol:\PLR
    * id:\enigma-project  symbol:\ENG
    * id:\mobilego  symbol:\MGO
    * id:\eidoo  symbol:\EDO
    * id:\humaniq  symbol:\HMQ
    * id:\poet  symbol:\POE
    * id:\lykke  symbol:\LKK
    * id:\firstblood  symbol:\1ST
    * id:\tierion  symbol:\TNT
    * id:\namecoin  symbol:\NMC
    * id:\ethlend  symbol:\LEND
    * id:\aeon  symbol:\AEON
    * id:\smartcash  symbol:\SMART
    * id:\wagerr  symbol:\WGR
    * id:\melon  symbol:\MLN
    * id:\emercoin  symbol:\EMC
    * id:\centra  symbol:\CTR
    * id:\coindash  symbol:\CDT
    * id:\paypex  symbol:\PAYX
    * id:\xtrabytes  symbol:\XBY
    * id:\dentacoin  symbol:\DCN
    * id:\supernet-unity  symbol:\UNITY
    * id:\faircoin  symbol:\FAIR
    * id:\district0x  symbol:\DNT
    * id:\crown  symbol:\CRW
    * id:\neblio  symbol:\NEBL
    * id:\gulden  symbol:\NLG
    * id:\guppy  symbol:\GUP
    * id:\blocktix  symbol:\TIX
    * id:\amber  symbol:\AMB
    * id:\decent  symbol:\DCT
    * id:\airswap  symbol:\AST
    * id:\trust  symbol:\TRST
    * id:\burst  symbol:\BURST
    * id:\sibcoin  symbol:\SIB
    * id:\etherparty  symbol:\FUEL
    * id:\steem-dollars  symbol:\SBD
    * id:\taas  symbol:\TAAS
    * id:\iocoin  symbol:\IOC
    * id:\bodhi  symbol:\BOT
    * id:\blockv  symbol:\VEE
    * id:\ion  symbol:\ION
    * id:\blackcoin  symbol:\BLK
    * id:\zeusshield  symbol:\ZSC
    * id:\spankchain  symbol:\SPANK
    * id:\okcash  symbol:\OK
    * id:\diamond  symbol:\DMD
    * id:\elastic  symbol:\XEL
    * id:\fedoracoin  symbol:\TIPS
    * id:\shift  symbol:\SHIFT
    * id:\open-trading-network  symbol:\OTN
    * id:\modum  symbol:\MOD
    * id:\triggers  symbol:\TRIG
    * id:\monetha  symbol:\MTH
    * id:\viberate  symbol:\VIB
    * id:\moeda-loyalty-points  symbol:\MDA
    * id:\nolimitcoin  symbol:\NLC2
    * id:\spectrecoin  symbol:\XSPEC
    * id:\bridgecoin  symbol:\BCO
    * id:\mysterium  symbol:\MYST
    * id:\patientory  symbol:\PTOY
    * id:\monetaryunit  symbol:\MUE
    * id:\synereo  symbol:\AMP
    * id:\omni  symbol:\OMNI
    * id:\numeraire  symbol:\NMR
    * id:\florincoin  symbol:\FLO
    * id:\bitcny  symbol:\BITCNY
    * id:\gridcoin  symbol:\GRC
    * id:\russian-mining-coin  symbol:\RMC
    * id:\grid  symbol:\GRID
    * id:\xplay  symbol:\XPA
    * id:\unikoin-gold  symbol:\UKG
    * id:\vericoin  symbol:\VRC
    * id:\salus  symbol:\SLS
    * id:\hempcoin  symbol:\THC
    * id:\waves-community-token  symbol:\WCT
    * id:\exchange-union  symbol:\XUC
    * id:\agrello-delta  symbol:\DLT
    * id:\bitcore  symbol:\BTX
    * id:\primas  symbol:\PST
    * id:\stox  symbol:\STX
    * id:\bitdice  symbol:\CSNO
    * id:\xp  symbol:\XP
    * id:\golos  symbol:\GOLOS
    * id:\oraclechain  symbol:\OCT
    * id:\paragon  symbol:\PRG
    * id:\clams  symbol:\CLAM
    * id:\radium  symbol:\RADS
    * id:\genesis-vision  symbol:\GVT
    * id:\obits  symbol:\OBITS
    * id:\firstcoin  symbol:\FRST
    * id:\bcap  symbol:\BCAP
    * id:\gambit  symbol:\GAM
    * id:\everex  symbol:\EVX
    * id:\rubycoin  symbol:\RBY
    * id:\global-currency-reserve  symbol:\GCR
    * id:\presearch  symbol:\PRE
    * id:\adtoken  symbol:\ADT
    * id:\bitsend  symbol:\BSD
    * id:\phore  symbol:\PHR
    * id:\ixledger  symbol:\IXT
    * id:\expanse  symbol:\EXP
    * id:\alis  symbol:\ALIS
    * id:\suncontract  symbol:\SNC
    * id:\mooncoin  symbol:\MOON
    * id:\neoscoin  symbol:\NEOS
    * id:\aventus  symbol:\AVT
    * id:\pascal-coin  symbol:\PASC
    * id:\databits  symbol:\DTB
    * id:\domraider  symbol:\DRT
    * id:\tokencard  symbol:\TKN
    * id:\incent  symbol:\INCNT
    * id:\atbcoin  symbol:\ATB
    * id:\mothership  symbol:\MSP
    * id:\transfercoin  symbol:\TX
    * id:\rialto  symbol:\XRL
    * id:\maecenas  symbol:\ART
    * id:\leocoin  symbol:\LEO
    * id:\credo  symbol:\CREDO
    * id:\foldingcoin  symbol:\FLDC
    * id:\nimiq  symbol:\NET
    * id:\bitqy  symbol:\BQ
    * id:\solarcoin  symbol:\SLR
    * id:\quantum  symbol:\QAU
    * id:\boolberry  symbol:\BBR
    * id:\lomocoin  symbol:\LMC
    * id:\unobtanium  symbol:\UNO
    * id:\icos  symbol:\ICOS
    * id:\kickico  symbol:\KICK
    * id:\nvo  symbol:\NVST
    * id:\peerplays-ppy  symbol:\PPY
    * id:\lunyr  symbol:\LUN
    * id:\vcash  symbol:\XVC
    * id:\obsidian  symbol:\ODN
    * id:\e-coin  symbol:\ECN
    * id:\swarm-city  symbol:\SWT
    * id:\xaurum  symbol:\XAUR
    * id:\real-estate-tokens  symbol:\REX
    * id:\rivetz  symbol:\RVT
    * id:\nexium  symbol:\NXC
    * id:\the-champcoin  symbol:\TCC
    * id:\heat-ledger  symbol:\HEAT
    * id:\etheroll  symbol:\DICE
    * id:\bitbean  symbol:\BITB
    * id:\posw-coin  symbol:\POSW
    * id:\soarcoin  symbol:\SOAR
    * id:\energycoin  symbol:\ENRG
    * id:\deeponion  symbol:\ONION
    * id:\sphere  symbol:\SPHR
    * id:\clearpoll  symbol:\POLL
    * id:\bitmark  symbol:\BTM
    * id:\memetic  symbol:\MEME
    * id:\musicoin  symbol:\MUSIC
    * id:\oxycoin  symbol:\OXY
    * id:\myriad  symbol:\XMY
    * id:\circuits-of-value  symbol:\COVAL
    * id:\bitusd  symbol:\BITUSD
    * id:\pinkcoin  symbol:\PINK
    * id:\blackmoon-crypto  symbol:\BMC
    * id:\novacoin  symbol:\NVC
    * id:\polybius  symbol:\PLBT
    * id:\sequence  symbol:\SEQ
    * id:\ethereum-movie-venture  symbol:\EMV
    * id:\korecoin  symbol:\KORE
    * id:\coss  symbol:\COSS
    * id:\curecoin  symbol:\CURE
    * id:\decision-token  symbol:\HST
    * id:\blockmason  symbol:\BCPT
    * id:\oax  symbol:\OAX
    * id:\bitzeny  symbol:\ZNY
    * id:\change  symbol:\CAG
    * id:\target-coin  symbol:\TGT
    * id:\bitcrystals  symbol:\BCY
    * id:\airtoken  symbol:\AIR
    * id:\chronobank  symbol:\TIME
    * id:\encrypgen  symbol:\DNA
    * id:\latoken  symbol:\LA
    * id:\nushares  symbol:\NSR
    * id:\martexcoin  symbol:\MXT
    * id:\goldcoin  symbol:\GLD
    * id:\astro  symbol:\ASTRO
    * id:\stealthcoin  symbol:\XST
    * id:\ethereum-blue  symbol:\BLUE
    * id:\auroracoin  symbol:\AUR
    * id:\masternodecoin  symbol:\MTNC
    * id:\xenon  symbol:\XNN
    * id:\dopecoin  symbol:\DOPE
    * id:\cvcoin  symbol:\CVCOIN
    * id:\bitcoin-plus  symbol:\XBC
    * id:\breakout  symbol:\BRK
    * id:\tao  symbol:\XTO
    * id:\internet-of-people  symbol:\IOP
    * id:\artbyte  symbol:\ABY
    * id:\lampix  symbol:\PIX
    * id:\decent-bet  symbol:\DBET
    * id:\vibe  symbol:\VIBE
    * id:\bitdeal  symbol:\BDL
    * id:\investfeed  symbol:\IFT
    * id:\toacoin  symbol:\TOA
    * id:\earthcoin  symbol:\EAC
    * id:\shield-xsh  symbol:\XSH
    * id:\prizm  symbol:\PZM
    * id:\e-dinar-coin  symbol:\EDR
    * id:\farad  symbol:\FRD
    * id:\blockcat  symbol:\CAT
    * id:\sexcoin  symbol:\SXC
    * id:\qwark  symbol:\QWARK
    * id:\pesetacoin  symbol:\PTC
    * id:\ebtcnew  symbol:\EBTC
    * id:\zephyr  symbol:\ZEPH
    * id:\syndicate  symbol:\SYNX
    * id:\aeron  symbol:\ARN
    * id:\yocoin  symbol:\YOC
    * id:\dynamic  symbol:\DYN
    * id:\hellogold  symbol:\HGT
    * id:\riecoin  symbol:\RIC
    * id:\apx  symbol:\APX
    * id:\primecoin  symbol:\XPM
    * id:\bonpay  symbol:\BON
    * id:\voisecom  symbol:\VOISE
    * id:\belacoin  symbol:\BELA
    * id:\exclusivecoin  symbol:\EXCL
    * id:\dubaicoin-dbix  symbol:\DBIX
    * id:\eccoin  symbol:\ECC
    * id:\b2bx  symbol:\B2B
    * id:\dao-casino  symbol:\BET
    * id:\ecobit  symbol:\ECOB
    * id:\project-decorum  symbol:\PDC
    * id:\dimecoin  symbol:\DIME
    * id:\zclassic  symbol:\ZCL
    * id:\europecoin  symbol:\ERC
    * id:\synergy  symbol:\SNRG
    * id:\dovu  symbol:\DOVU
    * id:\2give  symbol:\2GIVE
    * id:\trustplus  symbol:\TRUST
    * id:\mcap  symbol:\MCAP
    * id:\propy  symbol:\PRO
    * id:\primalbase  symbol:\PBT
    * id:\bitswift  symbol:\SWIFT
    * id:\breakout-stake  symbol:\BRX
    * id:\bluecoin  symbol:\BLU
    * id:\equitrader  symbol:\EQT
    * id:\pluton  symbol:\PLU
    * id:\ergo  symbol:\EFYT
    * id:\divi  symbol:\DIVX
    * id:\dcorp  symbol:\DRP
    * id:\elixir  symbol:\ELIX
    * id:\creditbit  symbol:\CRB
    * id:\vslice  symbol:\VSL
    * id:\htmlcoin  symbol:\HTML5
    * id:\mybit-token  symbol:\MYB
    * id:\evergreencoin  symbol:\EGC
    * id:\neutron  symbol:\NTRN
    * id:\atmos  symbol:\ATMS
    * id:\zrcoin  symbol:\ZRC
    * id:\alqo  symbol:\ALQO
    * id:\trezarcoin  symbol:\TZC
    * id:\putincoin  symbol:\PUT
    * id:\geocoin  symbol:\GEO
    * id:\flixxo  symbol:\FLIXX
    * id:\bitcloud  symbol:\BTDX
    * id:\cannabiscoin  symbol:\CANN
    * id:\thegcccoin  symbol:\GCC
    * id:\paccoin  symbol:\PAC
    * id:\blitzcash  symbol:\BLITZ
    * id:\blockpool  symbol:\BPL
    * id:\hush  symbol:\HUSH
    * id:\sharechain  symbol:\SSS
    * id:\startcoin  symbol:\START
    * id:\parkbyte  symbol:\PKB
    * id:\pirl  symbol:\PIRL
    * id:\adshares  symbol:\ADST
    * id:\veriumreserve  symbol:\VRM
    * id:\oceanlab  symbol:\OCL
    * id:\real  symbol:\REAL
    * id:\creativecoin  symbol:\CREA
    * id:\publica  symbol:\PBL
    * id:\indorse-token  symbol:\IND
    * id:\huntercoin  symbol:\HUC
    * id:\asiacoin  symbol:\AC
    * id:\gobyte  symbol:\GBX
    * id:\unbreakablecoin  symbol:\UNB
    * id:\chaincoin  symbol:\CHC
    * id:\mercury-protocol  symbol:\GMT
    * id:\vtorrent  symbol:\VTR
    * id:\internxt  symbol:\INXT
    * id:\innova  symbol:\INN
    * id:\autonio  symbol:\NIO
    * id:\karbowanec  symbol:\KRB
    * id:\quark  symbol:\QRK
    * id:\mintcoin  symbol:\MINT
    * id:\chips  symbol:\CHIPS
    * id:\trueflip  symbol:\TFL
    * id:\universal-currency  symbol:\UNIT
    * id:\onix  symbol:\ONX
    * id:\life  symbol:\LIFE
    * id:\darcrus  symbol:\DAR
    * id:\e-gulden  symbol:\EFL
    * id:\newyorkcoin  symbol:\NYC
    * id:\kolion  symbol:\KLN
    * id:\worldcoin  symbol:\WDC
    * id:\cryptonite  symbol:\XCN
    * id:\cryptoping  symbol:\PING
    * id:\dotcoin  symbol:\DOT
    * id:\centurion  symbol:\CNT
    * id:\smartbillions  symbol:\SMART
    * id:\tokes  symbol:\TKS
    * id:\terracoin  symbol:\TRC
    * id:\spreadcoin  symbol:\SPR
    * id:\rupee  symbol:\RUP
    * id:\megacoin  symbol:\MEC
    * id:\fundyourselfnow  symbol:\FYN
    * id:\anoncoin  symbol:\ANC
    * id:\magi  symbol:\XMG
    * id:\vivo  symbol:\VIVO
    * id:\luckchain  symbol:\BASH
    * id:\social  symbol:\SCL
    * id:\mywish  symbol:\WISH
    * id:\espers  symbol:\ESP
    * id:\crave  symbol:\CRAVE
    * id:\flypme  symbol:\FYP
    * id:\starta  symbol:\STA
    * id:\zennies  symbol:\ZENI
    * id:\smart-investment-fund-token  symbol:\SIFT
    * id:\cartaxi-token  symbol:\CTX
    * id:\luxcoin  symbol:\LUX
    * id:\linx  symbol:\LINX
    * id:\qvolta  symbol:\QVT
    * id:\pandacoin-pnd  symbol:\PND
    * id:\opus  symbol:\OPT
    * id:\ico-openledger  symbol:\ICOO
    * id:\goldblocks  symbol:\GB
    * id:\wavesgo  symbol:\WGO
    * id:\hyperstake  symbol:\HYP
    * id:\ufo-coin  symbol:\UFO
    * id:\supercoin  symbol:\SUPER
    * id:\bitcoin-red  symbol:\BTCRED
    * id:\atlant  symbol:\ATL
    * id:\ellaism  symbol:\ELLA
    * id:\hedge  symbol:\HDG
    * id:\audiocoin  symbol:\ADC
    * id:\altcoin-alt  symbol:\ALT
    * id:\dnotes  symbol:\NOTE
    * id:\1337coin  symbol:\1337
    * id:\ixcoin  symbol:\IXC
    * id:\solaris  symbol:\XLR
    * id:\42-coin  symbol:\42
    * id:\bitcoinz  symbol:\BTCZ
    * id:\sumokoin  symbol:\SUMO
    * id:\eboostcoin  symbol:\EBST
    * id:\tracto  symbol:\TRCT
    * id:\zoin  symbol:\ZOI
    * id:\intelligent-trading-tech  symbol:\ITT
    * id:\footy-cash  symbol:\XFT
    * id:\unitus  symbol:\UIS
    * id:\flik  symbol:\FLIK
    * id:\ethbits  symbol:\ETBS
    * id:\magnet  symbol:\MAG
    * id:\digipulse  symbol:\DGPT
    * id:\gcoin  symbol:\GCN
    * id:\legends-room  symbol:\LGD
    * id:\bata  symbol:\BTA
    * id:\buzzcoin  symbol:\BUZZ
    * id:\hubii-network  symbol:\HBT
    * id:\sprouts  symbol:\SPRTS
    * id:\britcoin  symbol:\BRIT
    * id:\woodcoin  symbol:\LOG
    * id:\greencoin  symbol:\GRE
    * id:\embers  symbol:\MBRS
    * id:\procurrency  symbol:\PROC
    * id:\miners-reward-token  symbol:\MRT
    * id:\erc20  symbol:\ERC20
    * id:\privatix  symbol:\PRIX
    * id:\cryptogenic-bullion  symbol:\CBX
    * id:\piplcoin  symbol:\PIPL
    * id:\monacocoin  symbol:\XMCC
    * id:\ongsocial  symbol:\ONG
    * id:\pure  symbol:\PURE
    * id:\bulwark  symbol:\BWK
    * id:\orbitcoin  symbol:\ORB
    * id:\zetacoin  symbol:\ZET
    * id:\zeitcoin  symbol:\ZEIT
    * id:\intensecoin  symbol:\ITNS
    * id:\visio  symbol:\VISIO
    * id:\bytecent  symbol:\BYC
    * id:\condensate  symbol:\RAIN
    * id:\fastcoin  symbol:\FST
    * id:\canada-ecoin  symbol:\CDN
    * id:\denarius-dnr  symbol:\DNR
    * id:\draftcoin  symbol:\DFT
    * id:\gimli  symbol:\GIM
    * id:\royal-kingdom-coin  symbol:\RKC
    * id:\unify  symbol:\UNIFY
    * id:\giga-watt-token  symbol:\WTT
    * id:\kekcoin  symbol:\KEK
    * id:\deutsche-emark  symbol:\DEM
    * id:\growers-international  symbol:\GRWI
    * id:\link-platform  symbol:\LNK
    * id:\monster-byte  symbol:\MBI
    * id:\influxcoin  symbol:\INFX
    * id:\cryptoforecast  symbol:\CFT
    * id:\unity-ingot  symbol:\UNY
    * id:\smileycoin  symbol:\SMLY
    * id:\adzcoin  symbol:\ADZ
    * id:\electra  symbol:\ECA
    * id:\bitcoin-scrypt  symbol:\BTCS
    * id:\biblepay  symbol:\BBP
    * id:\abjcoin  symbol:\ABJ
    * id:\fujicoin  symbol:\FJC
    * id:\inpay  symbol:\INPAY
    * id:\bitbar  symbol:\BTB
    * id:\xios  symbol:\XIOS
    * id:\payfair  symbol:\PFR
    * id:\nekonium  symbol:\NUKO
    * id:\arcticcoin  symbol:\ARC
    * id:\emphy  symbol:\EPY
    * id:\skincoin  symbol:\SKIN
    * id:\dashcoin  symbol:\DSH
    * id:\renos  symbol:\RNS
    * id:\hicoin  symbol:\XHI
    * id:\signatum  symbol:\SIGT
    * id:\oyster-pearl  symbol:\PRL
    * id:\noblecoin  symbol:\NOBL
    * id:\cryptocarbon  symbol:\CCRB
    * id:\digitalprice  symbol:\DP
    * id:\joulecoin  symbol:\XJO
    * id:\trollcoin  symbol:\TROLL
    * id:\mazacoin  symbol:\MZC
    * id:\trackr  symbol:\TKR
    * id:\interstellar-holdings  symbol:\HOLD
    * id:\zero  symbol:\ZER
    * id:\netcoin  symbol:\NET
    * id:\netko  symbol:\NETKO
    * id:\opal  symbol:\OPAL
    * id:\linda  symbol:\LINDA
    * id:\vsync-vsx  symbol:\VSX
    * id:\capricoin  symbol:\CPC
    * id:\moin  symbol:\MOIN
    * id:\tagcoin  symbol:\TAG
    * id:\litebar  symbol:\LTB
    * id:\gameunits  symbol:\UNITS
    * id:\remicoin  symbol:\RMC
    * id:\bitbtc  symbol:\BITBTC
    * id:\roulettetoken  symbol:\RLT
    * id:\starcredits  symbol:\STRC
    * id:\maxcoin  symbol:\MAX
    * id:\crowdcoin  symbol:\CRC
    * id:\authorship  symbol:\ATS
    * id:\insanecoin-insn  symbol:\INSN
    * id:\upfiring  symbol:\UFR
    * id:\postoken  symbol:\POS
    * id:\popularcoin  symbol:\POP
    * id:\litecoin-plus  symbol:\LCP
    * id:\litedoge  symbol:\LDOGE
    * id:\ultracoin  symbol:\UTC
    * id:\eltcoin  symbol:\ELTCOIN
    * id:\mao-zedong  symbol:\MAO
    * id:\catcoin  symbol:\CAT
    * id:\zozocoin  symbol:\ZZC
    * id:\happycoin  symbol:\HPC
    * id:\inflationcoin  symbol:\IFLT
    * id:\bitradio  symbol:\BRO
    * id:\carboncoin  symbol:\CARBON
    * id:\nubits  symbol:\USNBT
    * id:\copico  symbol:\XCPO
    * id:\fujinto  symbol:\NTO
    * id:\sovereign-hero  symbol:\HERO
    * id:\bigup  symbol:\BIGUP
    * id:\zurcoin  symbol:\ZUR
    * id:\phoenixcoin  symbol:\PXC
    * id:\atomic-coin  symbol:\ATOM
    * id:\digital-developers-fund  symbol:\DDF
    * id:\xgox  symbol:\XGOX
    * id:\fuelcoin  symbol:\FC2
    * id:\ccore  symbol:\CCO
    * id:\cream  symbol:\CRM
    * id:\goodomy  symbol:\GOOD
    * id:\petrodollar  symbol:\XPD
    * id:\accelerator-network  symbol:\ACC
    * id:\incakoin  symbol:\NKA
    * id:\bitboost  symbol:\BBT
    * id:\colossuscoinxt  symbol:\COLX
    * id:\redcoin  symbol:\RED
    * id:\kilocoin  symbol:\KLC
    * id:\bitcurrency  symbol:\BTCR
    * id:\teslacoin  symbol:\TES
    * id:\bitcoinfast  symbol:\BCF
    * id:\digitalcoin  symbol:\DGC
    * id:\minereum  symbol:\MNE
    * id:\trumpcoin  symbol:\TRUMP
    * id:\veltor  symbol:\VLT
    * id:\nyancoin  symbol:\NYAN
    * id:\crystal-clear  symbol:\CCT
    * id:\briacoin  symbol:\BRIA
    * id:\universe  symbol:\UNI
    * id:\8bit  symbol:\8BIT
    * id:\blockpay  symbol:\BLOCKPAY
    * id:\titcoin  symbol:\TIT
    * id:\ethbet  symbol:\EBET
    * id:\grimcoin  symbol:\GRIM
    * id:\embercoin  symbol:\EMB
    * id:\the-cypherfunks  symbol:\FUNK
    * id:\newbium  symbol:\NEWB
    * id:\altcommunity-coin  symbol:\ALTCOM
    * id:\icobid  symbol:\ICOB
    * id:\swagbucks  symbol:\BUCKS
    * id:\bitstar  symbol:\BITS
    * id:\pakcoin  symbol:\PAK
    * id:\hawla-today  symbol:\HAT
    * id:\photon  symbol:\PHO
    * id:\sterlingcoin  symbol:\SLG
    * id:\bit20  symbol:\BTWTY
    * id:\pascal-lite  symbol:\PASL
    * id:\ethereum-gold  symbol:\ETG
    * id:\kushcoin  symbol:\KUSH
    * id:\rasputin-online-coin  symbol:\ROC
    * id:\fluttercoin  symbol:\FLT
    * id:\hodlcoin  symbol:\HODL
    * id:\guncoin  symbol:\GUN
    * id:\freicoin  symbol:\FRC
    * id:\bunnycoin  symbol:\BUN
    * id:\boostcoin  symbol:\BOST
    * id:\whalecoin  symbol:\WHL
    * id:\tychocoin  symbol:\TYCHO
    * id:\ether-for-the-rest-of-the-world  symbol:\E4ROW
    * id:\triangles  symbol:\TRI
    * id:\paycoin2  symbol:\XPY
    * id:\qubitcoin  symbol:\Q2C
    * id:\eternity  symbol:\ENT
    * id:\tittiecoin  symbol:\TTC
    * id:\bolivarcoin  symbol:\BOLI
    * id:\evotion  symbol:\EVO
    * id:\globalboost-y  symbol:\BSTY
    * id:\helleniccoin  symbol:\HNC
    * id:\goldreserve  symbol:\XGR
    * id:\berncash  symbol:\BERN
    * id:\usde  symbol:\USDE
    * id:\piggycoin  symbol:\PIGGY
    * id:\bittokens  symbol:\BXT
    * id:\chancoin  symbol:\4CHN
    * id:\ethereumcash  symbol:\ECASH
    * id:\sagacoin  symbol:\SAGA
    * id:\jetcoin  symbol:\JET
    * id:\confido  symbol:\CFD
    * id:\cannation  symbol:\CNNC
    * id:\wyvern  symbol:\WYV
    * id:\bitsilver  symbol:\BITSILVER
    * id:\senderon  symbol:\SDRN
    * id:\blakestar  symbol:\BLAS
    * id:\platinumbar  symbol:\XPTX
    * id:\postcoin  symbol:\POST
    * id:\ebitcoin-cash  symbol:\EBCH
    * id:\eaglecoin  symbol:\EAGLE
    * id:\kittehcoin  symbol:\MEOW
    * id:\ethereum-dark  symbol:\ETHD
    * id:\bitcoin-planet  symbol:\BTPL
    * id:\unrealcoin  symbol:\URC
    * id:\ratecoin  symbol:\XRA
    * id:\bumbacoin  symbol:\BUMBA
    * id:\lanacoin  symbol:\LANA
    * id:\dalecoin  symbol:\DALC
    * id:\808coin  symbol:\808
    * id:\blakecoin  symbol:\BLC
    * id:\bitgem  symbol:\BTG
    * id:\elcoin-el  symbol:\EL
    * id:\ecocoin  symbol:\ECO
    * id:\zcash-gold  symbol:\ZCG
    * id:\campuscoin  symbol:\CMPCO
    * id:\macron  symbol:\MCRN
    * id:\leviarcoin  symbol:\XLC
    * id:\octocoin  symbol:\888
    * id:\virtacoinplus  symbol:\XVP
    * id:\sugar-exchange  symbol:\SGR
    * id:\iethereum  symbol:\IETH
    * id:\hempcoin-hmp  symbol:\HMP
    * id:\billionaire-token  symbol:\XBL
    * id:\bitasean  symbol:\BAS
    * id:\goldpieces  symbol:\GP
    * id:\impact  symbol:\IMX
    * id:\eot-token  symbol:\EOT
    * id:\bitcoal  symbol:\COAL
    * id:\debitcoin  symbol:\DBTC
    * id:\coinonatx  symbol:\XCXT
    * id:\cryptojacks  symbol:\CJ
    * id:\nevacoin  symbol:\NEVA
    * id:\scorecoin  symbol:\SCORE
    * id:\eurocoin  symbol:\EUC
    * id:\ripto-bux  symbol:\RBX
    * id:\aerium  symbol:\AERM
    * id:\droxne  symbol:\DRXNE
    * id:\argentum  symbol:\ARG
    * id:\gpu-coin  symbol:\GPU
    * id:\mutual-coin  symbol:\MUT
    * id:\300-token  symbol:\300
    * id:\votecoin  symbol:\VOT
    * id:\cachecoin  symbol:\CACH
    * id:\virta-unique-coin  symbol:\VUC
    * id:\funcoin  symbol:\FUNC
    * id:\bolenum  symbol:\BLN
    * id:\honey  symbol:\HONEY
    * id:\sixeleven  symbol:\611
    * id:\monkey-project  symbol:\MONK
    * id:\litecred  symbol:\LTCR
    * id:\comet  symbol:\CMT
    * id:\compucoin  symbol:\CPN
    * id:\securecoin  symbol:\SRC
    * id:\idice  symbol:\ICE
    * id:\globaltoken  symbol:\GLT
    * id:\global-tour-coin  symbol:\GTC
    * id:\bitgold  symbol:\BITGOLD
    * id:\prcoin  symbol:\PRC
    * id:\biteur  symbol:\BITEUR
    * id:\corgicoin  symbol:\CORG
    * id: \money" symbol:\$$$
    * id:\gold-pressed-latinum  symbol:\GPL
    * id:\marijuanacoin  symbol:\MAR
    * id:\bipcoin  symbol:\BIP
    * id:\spots  symbol:\SPT
    * id:\anarchistsprime  symbol:\ACP
    * id:\luna-coin  symbol:\LUNA
    * id:\neuro  symbol:\NRO
    * id:\kayicoin  symbol:\KAYI
    * id:\reecoin  symbol:\REE
    * id:\kurrent  symbol:\KURT
    * id:\ethgas  symbol:\EGAS
    * id:\eryllium  symbol:\ERY
    * id:\billarycoin  symbol:\BLRY
    * id:\litecoin-ultra  symbol:\LTCU
    * id:\benjirolls  symbol:\BENJI
    * id:\doubloon  symbol:\BOAT
    * id:\litebitcoin  symbol:\LBTC
    * id:\credence-coin  symbol:\CRDNC
    * id:\interzone  symbol:\ITZ
    * id:\tekcoin  symbol:\TEK
    * id:\rimbit  symbol:\RBT
    * id:\ereal  symbol:\EREAL
    * id:\women  symbol:\WOMEN
    * id:\iconic  symbol:\ICON
    * id:\master-swiscoin  symbol:\MSCN
    * id:\solarflarecoin  symbol:\SFC
    * id:\veros  symbol:\VRS
    * id:\bnrtxcoin  symbol:\BNX
    * id:\genstake  symbol:\G3N
    * id:\brat  symbol:\BRAT
    * id:\agrolifecoin  symbol:\AGLC
    * id:\crevacoin  symbol:\CREVA
    * id:\futurexe  symbol:\FXE
    * id:\antilitecoin  symbol:\ALTC
    * id:\argus  symbol:\ARGUS
    * id:\cybcsec  symbol:\XCS
    * id:\levoplus  symbol:\LVPS
    * id:\magnum  symbol:\MGM
    * id:\geysercoin  symbol:\GSR
    * id:\rawcoin2  symbol:\XRC
    * id:\corethum  symbol:\CRTM
    * id:\harmonycoin-hmc  symbol:\HMC
    * id:\ebittree-coin  symbol:\EBT
    * id:\digital-money-bits  symbol:\DMB
    * id:\prospectors-gold  symbol:\PGL
    * id:\encryptotel  symbol:\ETT
    * id:\stakecoin-stcn  symbol:\STCN
    * id:\bismuth  symbol:\BIS
    * id:\xcurrency  symbol:\XC
    * id:\fimkrypto  symbol:\FIMK
    * id:\neverdie  symbol:\NDC
    * id:\bankcoin  symbol:\B@
    * id:\rustbits  symbol:\RUSTBITS
    * id:\yashcoin  symbol:\YASH
    * id:\adelphoi  symbol:\ADL
    * id:\fantomcoin  symbol:\FCN
    * id:\colossuscoin-v2  symbol:\CV2
    * id:\cryptcoin  symbol:\CRYPT
    * id:\bitland  symbol:\CADASTRAL
    * id:\elementrem  symbol:\ELE
    * id:\arcade-token  symbol:\ARC
    * id:\etheriya  symbol:\RIYA
    * id:\hitcoin  symbol:\HTC
    * id:\russiacoin  symbol:\RC
    * id:\shorty  symbol:\SHORTY
    * id:\janus  symbol:\JNS
    * id:\metalcoin  symbol:\METAL
    * id:\ultimate-secure-cash  symbol:\USC
    * id:\kobocoin  symbol:\KOBO
    * id:\bowhead  symbol:\AHT
    * id:\coin  symbol:\CNO
    * id:\shadowcash  symbol:\SDC
    * id:\casino  symbol:\CASINO
    * id:\btsr  symbol:\BTSR
    * id:\dinastycoin  symbol:\DCY
    * id:\bitpark-coin  symbol:\BPC
    * id:\valorbit  symbol:\VAL
    * id:\hobonickels  symbol:\HBN
    * id:\joincoin  symbol:\J
    * id:\smartcoin  symbol:\SMC
    * id:\machinecoin  symbol:\MAC
    * id:\version  symbol:\V
    * id:\stress  symbol:\STS
    * id:\unicoin  symbol:\UNIC
    * id:\octanox  symbol:\OTX
    * id:\i0coin  symbol:\I0C
    * id:\lottocoin  symbol:\LOT
    * id:\gaia  symbol:\GAIA
    * id:\cannacoin  symbol:\CCN
    * id:\daxxcoin  symbol:\DAXX
    * id:\wayguide  symbol:\WAY
    * id:\btctalkcoin  symbol:\TALK
    * id:\aurumcoin  symbol:\AU
    * id:\shadow-token  symbol:\SHDW
    * id:\sproutsextreme  symbol:\SPEX
    * id:\ohm-wallet  symbol:\OHM
    * id:\fucktoken  symbol:\FUCK
    * id:\iticoin  symbol:\ITI
    * id:\chesscoin  symbol:\CHESS
    * id:\sacoin  symbol:\SAC
    * id:\shilling  symbol:\SH
    * id:\flycoin  symbol:\FLY
    * id:\coexistcoin  symbol:\COXST
    * id:\digicube  symbol:\CUBE
    * id:\coin2-1  symbol:\C2
    * id:\sativacoin  symbol:\STV
    * id:\globalcoin  symbol:\GLC
    * id:\prototanium  symbol:\PR
    * id:\tigercoin  symbol:\TGC
    * id:\swing  symbol:\SWING
    * id:\icoin  symbol:\ICN
    * id:\truckcoin  symbol:\TRK
    * id:\halcyon  symbol:\HAL
    * id:\satoshimadness  symbol:\MAD
    * id:\purevidz  symbol:\VIDZ
    * id:\ambercoin  symbol:\AMBER
    * id:\spacecoin  symbol:\SPACE
    * id:\gapcoin  symbol:\GAP
    * id:\parallelcoin  symbol:\DUO
    * id:\philosopher-stones  symbol:\PHS
    * id:\fincoin  symbol:\FNC
    * id:\wmcoin  symbol:\WMC
    * id:\emerald  symbol:\EMD
    * id:\rubies  symbol:\RBIES
    * id:\acoin  symbol:\ACOIN
    * id:\mincoin  symbol:\MNC
    * id:\evil-coin  symbol:\EVIL
    * id:\mojocoin  symbol:\MOJO
    * id:\darsek  symbol:\KED
    * id:\px  symbol:\PX
    * id:\bitcoin-21  symbol:\XBTC21
    * id:\yacoin  symbol:\YAC
    * id:\marscoin  symbol:\MARS
    * id:\franko  symbol:\FRK
    * id:\aricoin  symbol:\ARI
    * id:\grantcoin  symbol:\GRT
    * id:\quatloo  symbol:\QTL
    * id:\prime-xi  symbol:\PXI
    * id:\creatio  symbol:\XCRE
    * id:\leacoin  symbol:\LEA
    * id:\antibitcoin  symbol:\ANTI
    * id:\c-bit  symbol:\XCT
    * id:\quazarcoin  symbol:\QCN
    * id:\mineum  symbol:\MNM
    * id:\cypher  symbol:\CYP
    * id:\islacoin  symbol:\ISL
    * id:\firecoin  symbol:\FIRE
    * id:\chronos  symbol:\CRX
    * id:\dollarcoin  symbol:\DLC
    * id:\tajcoin  symbol:\TAJ
    * id:\hexx  symbol:\HXX
    * id:\aquariuscoin  symbol:\ARCO
    * id:\sooncoin  symbol:\SOON
    * id:\sling  symbol:\SLING
    * id:\metal-music-coin  symbol:\MTLMC3
    * id:\revolvercoin  symbol:\XRE
    * id:\tattoocoin  symbol:\TSE
    * id:\ganjacoin  symbol:\MRJA
    * id:\bitz  symbol:\BITZ
    * id:\rupaya  symbol:\RUPX
    * id:\paycon  symbol:\CON
    * id:\jin-coin  symbol:\JIN
    * id:\allion  symbol:\ALL
    * id:\uro  symbol:\URO
    * id:\blazecoin  symbol:\BLZ
    * id:\vector  symbol:\VEC2
    * id:\secretcoin  symbol:\SCRT
    * id:\californium  symbol:\CF
    * id:\ronpaulcoin  symbol:\RPC
    * id:\independent-money-system  symbol:\IMS
    * id:\guccionecoin  symbol:\GCC
    * id:\mustangcoin  symbol:\MST
    * id:\blackstar  symbol:\BSTAR
    * id:\jewels  symbol:\JWL
    * id:\flaxscript  symbol:\FLAX
    * id:\crypto  symbol:\CTO
    * id:\virtualcoin  symbol:\VC
    * id:\zetamicron  symbol:\ZMC
    * id:\soilcoin  symbol:\SOIL
    * id:\slimcoin  symbol:\SLM
    * id:\mindcoin  symbol:\MND
    * id:\virtacoin  symbol:\VTA
    * id:\dreamcoin  symbol:\DRM
    * id:\emoneypower  symbol:\EMP
    * id:\beavercoin  symbol:\BVC
    * id:\warp  symbol:\WARP
    * id:\allsafe  symbol:\ASAFE2
    * id:\digital-rupees  symbol:\DRS
    * id:\coinonat  symbol:\CXT
    * id:\qibuck-asset  symbol:\QBK
    * id:\dibcoin  symbol:\DIBC
    * id:\theresa-may-coin  symbol:\MAY
    * id:\torcoin-tor  symbol:\TOR
    * id:\ammo-rewards  symbol:\AMMO
    * id:\pulse  symbol:\PULSE
    * id:\artex-coin  symbol:\ATX
    * id:\cagecoin  symbol:\CAGE
    * id:\cthulhu-offerings  symbol:\OFF
    * id:\cryptoworldx-token  symbol:\CWXT
    * id:\vip-tokens  symbol:\VIP
    * id:\printerium  symbol:\PRX
    * id:\bowscoin  symbol:\BSC
    * id:\crtcoin  symbol:\CRT
    * id:\asiadigicoin  symbol:\ADCN
    * id:\osmiumcoin  symbol:\OS76
    * id:\orlycoin  symbol:\ORLY
    * id:\fuzzballs  symbol:\FUZZ
    * id:\beatcoin  symbol:\XBTS
    * id:\piecoin  symbol:\PIE
    * id:\tagrcoin  symbol:\TAGR
    * id:\vaperscoin  symbol:\VPRC
    * id:\x-coin  symbol:\XCO
    * id:\healthywormcoin  symbol:\WORM
    * id:\plncoin  symbol:\PLNC
    * id:\flavorcoin  symbol:\FLVR
    * id:\destiny  symbol:\DES
    * id:\bitquark  symbol:\BTQ
    * id:\ponzicoin  symbol:\PONZI
    * id:\kronecoin  symbol:\KRONE
    * id:\ego  symbol:\EGO
    * id:\dappster  symbol:\DLISK
    * id:\zayedcoin  symbol:\ZYD
    * id:\impulsecoin  symbol:\IMPS
    * id:\useless-ethereum-token  symbol:\UET
    * id:\kibicoin  symbol:\KIC
    * id:\bios-crypto  symbol:\BIOS
    * id:\cashcoin  symbol:\CASH
    * id:\steps  symbol:\STEPS
    * id:\songcoin  symbol:\SONG
    * id:\roofs  symbol:\ROOFS
    * id:\chncoin  symbol:\CNC
    * id:\letitride  symbol:\LIR
    * id:\posex  symbol:\PEX
    * id:\dix-asset  symbol:\DIX
    * id:\arbit  symbol:\ARB
    * id:\dpay  symbol:\DPAY
    * id:\dollar-online  symbol:\DOLLAR
    * id:\network-token  symbol:\NTWK
    * id:\gamebet-coin  symbol:\GBT
    * id:\jobscoin  symbol:\JOBS
    * id:\playercoin  symbol:\PLACO
    * id:\slevin  symbol:\SLEVIN
    * id:\swaptoken  symbol:\TOKEN
    * id:\milocoin  symbol:\MILO
    * id:\ride-my-car  symbol:\RIDE
    * id:\mtmgaming  symbol:\MTM
    * id:\exchangen  symbol:\EXN
    * id:\vault-coin  symbol:\VLTC
    * id:\zonecoin  symbol:\ZNE
    * id:\cabbage  symbol:\CAB
    * id:\speedcash  symbol:\SCS
    * id:\biobar  symbol:\BIOB
    * id:\high-voltage  symbol:\HVCO
    * id:\braincoin  symbol:\BRAIN
    * id:\cryptoescudo  symbol:\CESC
    * id:\wild-beast-block  symbol:\WBB
    * id:\sydpak  symbol:\SDP
    * id:\ccminer  symbol:\CCM100
    * id:\rsgpcoin  symbol:\RSGP
    * id:\kingn-coin  symbol:\KNC
    * id:\ibank  symbol:\IBANK
    * id:\gbcgoldcoin  symbol:\GBC
    * id:\xonecoin  symbol:\XOC
    * id:\javascript-token  symbol:\JS
    * id:\selfiecoin  symbol:\SLFI
    * id:\burstocean  symbol:\OCEAN
    * id:\socialcoin-socc  symbol:\SOCC
    * id:\elysium  symbol:\ELS
    * id:\geertcoin  symbol:\GEERT
    * id:\bitvolt  symbol:\VOLT
    * id:\frazcoin  symbol:\FRAZ
    * id:\p7coin  symbol:\P7C
    * id:\das  symbol:\DAS
    * id:\morningstar-payments  symbol:\MRNG
    * id:\save-and-gain  symbol:\SANDG
    * id:\lex4all  symbol:\LEX
    * id:\coimatic-2  symbol:\CTIC2
    * id:\project-x  symbol:\NANOX
    * id:\nodecoin  symbol:\NODC
    * id:\sojourn  symbol:\SOJ
    * id:\concoin  symbol:\CONX
    * id:\ulatech  symbol:\ULA
    * id:\tradecoin-v2  symbol:\TRADE
    * id:\pizzacoin  symbol:\PIZZA
    * id:\enigma  symbol:\XNG
    * id:\wallet-builders-coin  symbol:\WBC
    * id:\tristar-coin  symbol:\TSTR
    * id:\digital-credits  symbol:\DGCS
    * id:\abncoin  symbol:\ABN
    * id:\mantracoin  symbol:\MNC
    * id:\environ  symbol:\ENV
    * id:\caliphcoin  symbol:\CALC
    * id:\falcoin  symbol:\FAL
    * id:\future-digital-currency  symbol:\FDC
    * id:\applecoin-apw  symbol:\APW
    * id:\icon  symbol:\ICX
    * id:\atmcoin  symbol:\ATMC
    * id:\gifto  symbol:\GTO
    * id:\cybermiles  symbol:\CMT
    * id:\smartmesh  symbol:\SMT
    * id:\nuls  symbol:\NULS
    * id:\bitcoin-diamond  symbol:\BCD
    * id:\genaro-network  symbol:\GNX
    * id:\bitcoinx  symbol:\BCX
    * id:\comsa-eth  symbol:\CMS
    * id:\poly-ai  symbol:\AI
    * id:\medishares  symbol:\MDS
    * id:\iot-chain  symbol:\ITC
    * id:\comsa-xem  symbol:\CMS
    * id:\regalcoin  symbol:\REC
    * id:\datum  symbol:\DAT
    * id:\lltoken  symbol:\LLT
    * id:\super-bitcoin  symbol:\SBTC
    * id:\infchain  symbol:\INF
    * id:\fargocoin  symbol:\FRGC
    * id:\prochain  symbol:\PRO
    * id:\clubcoin  symbol:\CLUB
    * id:\qbao  symbol:\QBT
    * id:\ormeus-coin  symbol:\ORME
    * id:\energo  symbol:\TSL
    * id:\golos-gold  symbol:\GBG
    * id:\eroscoin  symbol:\ERO
    * id:\filecoin  symbol:\FIL
    * id:\hollywoodcoin  symbol:\HWC
    * id:\win-coin  symbol:\WC
    * id:\viuly  symbol:\VIU
    * id:\santa-coin  symbol:\STC
    * id:\gold-reward-token  symbol:\GRX
    * id:\maker  symbol:\MKR
    * id:\micromoney  symbol:\AMM
    * id:\ug-token  symbol:\UGT
    * id:\bitserial  symbol:\BTE
    * id:\sportyfi  symbol:\SPF
    * id:\bitcoin-unlimited  symbol:\BTU
    * id:\dutch-coin  symbol:\DUTCH
    * id:\infinity-economics  symbol:\XIN
    * id:\anryze  symbol:\RYZ
    * id:\united-bitcoin  symbol:\UBTC
    * id:\sphre-air  symbol:\XID
    * id:\bt2-cst  symbol:\BT2
    * id:\vpncoin  symbol:\VASH
    * id:\b3coin  symbol:\B3
    * id:\techshares  symbol:\THS
    * id:\strikebitclub  symbol:\SBC
    * id:\worldcore  symbol:\WRC
    * id:\davorcoin  symbol:\DAV
    * id:\deuscoin  symbol:\DEUS
    * id:\stronghands  symbol:\SHND
    * id:\verify  symbol:\CRED
    * id:\dfscoin  symbol:\DFS
    * id:\bitsoar  symbol:\BSR
    * id:\uquid-coin  symbol:\UQC
    * id:\social-send  symbol:\SEND
    * id:\litecoin-gold  symbol:\LTG
    * id:\tokugawa  symbol:\TOK
    * id:\snovio  symbol:\SNOV
    * id:\ea-coin  symbol:\EAG
    * id:\ethereum-lite  symbol:\ELITE
    * id:\desire  symbol:\DSR
    * id:\bt1-cst  symbol:\BT1
    * id:\wild-crypto  symbol:\WILD
    * id:\sigmacoin  symbol:\SIGMA
    * id:\blockcdn  symbol:\BCDN
    * id:\zengold  symbol:\ZENGOLD
    * id:\yenten  symbol:\YTN
    * id:\mergecoin  symbol:\MGC
    * id:\mavro  symbol:\MAVRO
    * id:\pioneer-coin  symbol:\PCOIN
    * id:\sisa  symbol:\SISA
    * id:\btcmoon  symbol:\BTCM
    * id:\netbit  symbol:\NBIT
    * id:\msd  symbol:\MSD
    * id:\everus  symbol:\EVR
    * id:\blockchain-index  symbol:\BLX
    * id:\force  symbol:\FOR
    * id:\infinitecoin  symbol:\IFC
    * id:\advanced-internet-blocks  symbol:\AIB
    * id:\prismchain  symbol:\PRM
    * id:\akuya-coin  symbol:\AKY
    * id:\t-coin  symbol:\TCOIN
    * id:\sand-coin  symbol:\SND
    * id:\compcoin  symbol:\CMP
    * id:\corion  symbol:\COR
    * id:\macro1  symbol:\MCR
    * id:\peacecoin  symbol:\PEC
    * id:\neo-gold  symbol:\NEOG
    * id:\phantomx  symbol:\PNX
    * id:\musiconomi  symbol:\MCI
    * id:\zilbercoin  symbol:\ZBC
    * id:\chronologic  symbol:\DAY
    * id:\plexcoin  symbol:\PLX
    * id:\motocoin  symbol:\MOTO
    * id:\student-coin  symbol:\STU
    * id:\triaconta  symbol:\TRIA
    * id:\high-gain  symbol:\HIGH
    * id:\batcoin  symbol:\BAT
    * id:\vulcano  symbol:\VULC
    * id:\cashme  symbol:\CME
    * id:\dynamiccoin  symbol:\DMC
    * id:\bitcoin2x  symbol:\BTC2X
    * id:\glasscoin  symbol:\GLS
    * id:\terranova  symbol:\TER
    * id:\topaz  symbol:\TOPAZ
    * id:\digital-bullion-gold  symbol:\DBG
    * id:\sharkcoin  symbol:\SAK
    * id:\alphabitcoinfund  symbol:\ABC
    * id:\namocoin  symbol:\NAMO
    * id:\exrnchain  symbol:\EXRN
    * id:\flash  symbol:\FLASH
    * id:\pirate-blocks  symbol:\SKULL
    * id:\hyper-tv  symbol:\HYTV
    * id:\rcoin  symbol:\RCN
    * id:\suretly  symbol:\SUR
    * id:\hodl-bucks  symbol:\HDLB
    * id:\trident  symbol:\TRDT
    * id:\sakuracoin  symbol:\SKR
    * id:\flappycoin  symbol:\FLAP
    * id:\ibtc  symbol:\IBTC
    * id:\adcoin  symbol:\ACC
    * id:\ties-network  symbol:\TIE
    * id:\karmacoin  symbol:\KARMA
    * id:\bitbase  symbol:\BTBc
    * id:\bestchain  symbol:\BEST
    * id:\first-bitcoin-capital  symbol:\BITCF
    * id:\primulon  symbol:\PRIMU
    * id:\antimatter  symbol:\ANTX
    * id:\bitcoin-silver  symbol:\BTCS
    * id:\betacoin  symbol:\BET
    * id:\ocow  symbol:\OCOW
    * id:\india-coin  symbol:\INDIA
    * id:\eventchain  symbol:\EVC
    * id:\eggcoin  symbol:\EGG
    * id:\wink  symbol:\WINK
    * id:\pluscoin  symbol:\PLC
    * id:\pabyosi-coin-special  symbol:\PCS
    * id:\gaycoin  symbol:\GAY
    * id:\tellurion  symbol:\TELL
    * id:\uahpay  symbol:\UAHPAY
    * id:\internet-of-things  symbol:\XOT
    * id:\landcoin  symbol:\LDCN
    * id:\ox-fina  symbol:\OX
    * id:\cheapcoin  symbol:\CHEAP
    * id:\dimoncoin  symbol:\FUDD
    * id:\bubble  symbol:\BUB
    * id:\happy-creator-coin  symbol:\HCC
    * id:\universalroyalcoin  symbol:\UNRC
    * id:\animecoin  symbol:\ANI
    * id:\fapcoin  symbol:\FAP
    * id:\global-business-revolution  symbol:\GBRC
    * id:\encryptotel-eth  symbol:\ETT
    * id:\omicron  symbol:\OMC
    * id:\zsecoin  symbol:\ZSE
    * id:\francs  symbol:\FRN
    * id:\voyacoin  symbol:\VOYA
    * id:\minex  symbol:\MINEX
    * id:\topcoin  symbol:\TOP
    * id:\iquant  symbol:\IQT
    * id:\coupecoin  symbol:\COUPE
    * id:\ebit  symbol:\EBIT
    * id:\shacoin  symbol:\SHA
    * id:\irishcoin  symbol:\IRL
    * id:\safecoin  symbol:\SFE
    * id:\wa-space  symbol:\WA
    * id:\coimatic-3  symbol:\CTIC3
    * id:\royalties  symbol:\XRY
    * id:\elacoin  symbol:\ELC
    * id:\wi-coin  symbol:\WIC
    * id:\9coin  symbol:\9COIN
    * id:\ur  symbol:\UR
    * id:\donationcoin  symbol:\DON
    * id:\huncoin  symbol:\HNC
    * id:\bitcedi  symbol:\BXC
    * id:\fonziecoin  symbol:\FONZ
    * id:\eusd  symbol:\EUSD
    * id:\dashs  symbol:\DASHS
    * id:\amsterdamcoin  symbol:\AMS
    * id:\lazaruscoin  symbol:\LAZ
    * id:\halloween-coin  symbol:\HALLO
    * id:\rabbitcoin  symbol:\RBBT
    * id:\uncoin  symbol:\UNC
    * id:\cubits  symbol:\QBT
    * id:\wearesatoshi  symbol:\WSX
    * id:\alpacoin  symbol:\APC
    * id:\protean  symbol:\PRN
    * id:\avoncoin  symbol:\ACN
    * id:\cash-poker-pro  symbol:\CASH
    * id:\aces  symbol:\ACES
    * id:\gulfcoin  symbol:\MGC
    * id:\futcoin  symbol:\FUTC
    * id:\first-bitcoin  symbol:\BIT
    * id:\international-diamond  symbol:\XID
    * id:\natcoin  symbol:\NTC
    * id:\infinity-pay  symbol:\IPY
    * id:\qora  symbol:\QORA
    * id:\teamup  symbol:\TEAM
    * id:\skeincoin  symbol:\SKC
    * id:\egold  symbol:\EGOLD
    * id:\wowcoin  symbol:\WOW
    * id:\yescoin  symbol:\YES
    * id:\regacoin  symbol:\REGA
    * id:\moneycoin  symbol:\MONEY
    * id:\eltc  symbol:\ELTC2
    * id:\swapcoin  symbol:\SWP
    * id:\todaycoin  symbol:\TODAY
    * id:\president-trump  symbol:\PRES
    * id:\goldmaxcoin  symbol:\GMX
    * id:\bastonet  symbol:\BSN
    * id:\royalcoin  symbol:\ROYAL
    * id:\trickycoin  symbol:\TRICK
    * id:\axiom  symbol:\AXIOM
    * id:\pinkdog  symbol:\PDG
    * id:\moneta2  symbol:\MONETA
    * id:\cycling-coin  symbol:\CYC
    * id:\edrcoin  symbol:\EDRC
    * id:\marxcoin  symbol:\MARX
    * id:\lepen  symbol:\LEPEN
    * id:\rhfcoin  symbol:\RHFC
    * id:\runners  symbol:\RUNNERS
    * id:\blazercoin  symbol:\BLAZR
    * id:\facecoin  symbol:\FC
    * id:\turbocoin  symbol:\TURBO
    * id:\cyder  symbol:\CYDER
    * id:\granitecoin  symbol:\GRN
    * id:\rupaya-old  symbol:\RUPX
    * id:\fazzcoin  symbol:\FAZZ
    * id:\frankywillcoin  symbol:\FRWC
    * id:\xtd-coin  symbol:\XTD
    * id:\starcash-network  symbol:\STARS
    * id:\stex  symbol:\STEX
    * id:\bitalphacoin  symbol:\BAC
    * id:\ugain  symbol:\GAIN
    * id:\golfcoin  symbol:\GOLF
    * id:\opescoin  symbol:\OPES
    * id:\dubstep  symbol:\DUB
    * id:\gameleaguecoin  symbol:\GML
    * id:\teslacoilcoin  symbol:\TESLA
    * id:\avatarcoin  symbol:\AV
    * id:\rublebit  symbol:\RUBIT
    * id:\cbd-crystals  symbol:\CBD
    * id:\birds  symbol:\BIRDS
    * id:\bitok  symbol:\BITOK
    * id:\utacoin  symbol:\UTA
    * id:\x2  symbol:\X2
    * id:\magnetcoin  symbol:\MAGN
    * id:\fireflycoin  symbol:\FFC
    * id:\faceblock  symbol:\FBL
    * id:\quotient  symbol:\XQN
    * id:\linkedcoin  symbol:\LKC
    * id:\invisiblecoin  symbol:\IVZ
    * id:\thecreed  symbol:\TCR
    * id:\quebecoin  symbol:\QBC
    * id:\10mtoken  symbol:\10MT
    * id:\clinton  symbol:\CLINT
    * id:\snakeeyes  symbol:\SNAKE
    * id:\mobilecash  symbol:\MBL
    * id:\yellow-token  symbol:\YEL
    * id:\darklisk  symbol:\DISK
    * id:\richcoin  symbol:\RICHX
    * id:\xde-ii  symbol:\XDE2
    * id:\hyper  symbol:\HYPER
    * id:\peepcoin  symbol:\PCN
    * id:\lathaan  symbol:\LTH
    * id:\safe-trade-coin  symbol:\XSTC
    * id:\vegascoin  symbol:\VGC
    * id:\sync  symbol:\SYNC
    * id:\storjcoin-x  symbol:\SJCX
    * id:\bongger  symbol:\BGR
    * id:\bitcentavo  symbol:\NBE
    * id:\xaucoin  symbol:\XAU
    * id:\cybercoin  symbol:\CC
    * id:\shellcoin  symbol:\SHELL
    * id:\deltacredits  symbol:\DCRE
    * id:\safe-exchange-coin  symbol:\SAFEX
    * id:\mmxvi  symbol:\MMXVI
    * id:\psilocybin  symbol:\PSY
    * id:\paypeer  symbol:\PAYP
    * id:\operand  symbol:\OP
    * id:\pokecoin  symbol:\POKE
    * id:\president-johnson  symbol:\GARY
    * id:\sportscoin  symbol:\SPORT
    * id:\kashhcoin  symbol:\KASHH
    * id:\teracoin  symbol:\TERA
    * id:\the-vegan-initiative  symbol:\XVE
    * id:\bixc  symbol:\BIXC
    * id:\tattoocoin-limited  symbol:\TLE
    * id:\goldunioncoin  symbol:\GUC
    * id:\tyrocoin  symbol:\TYC
    * id:\picoin  symbol:\PI
    * id:\aidos-kuneen  symbol:\ADK
    * id:\peoplecoin  symbol:\MEN
    * id:\aseancoin  symbol:\ASN
    * id:\bitfid  symbol:\FID
    * id:\bitcoincashscrypt  symbol:\BCCS
    * id:\magiccoin  symbol:\MAGE
    * id:\xylo  symbol:\XYLO
    * id:\casinocoin  symbol:\CSC
    * id:\wowecoin  symbol:\WEC
    * id:\tezos  symbol:\XTZ
    * id:\swisscoin  symbol:\SIC
    * id:\etherdoge  symbol:\EDOGE
    * id:\segwit2x  symbol:\B2X
    * id:\boscoin  symbol:\BOS
    * id:\cappasity  symbol:\CAPP
    * id:\kubera-coin  symbol:\KBR
    * id:\ignis  symbol:\IGNIS
    * id:\bitair  symbol:\BTCA
    * id:\lockchain  symbol:\LO
]

@symbol-to-id=->
    for item in coins-array!
        if it == item.symbol => return item?id
    return null
